# Generated by Django 4.0.6 on 2022-08-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imageLink',
            field=models.URLField(),
        ),
    ]
