# Generated by Django 4.0.6 on 2022-08-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_project_imagelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imageLink',
            new_name='image',
        ),
    ]
