# Generated by Django 4.0.6 on 2022-08-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_rename_imagelink_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Projectlink',
            new_name='url',
        ),
    ]
