# Generated by Django 4.0.6 on 2022-08-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_account_user'),
        ('MyApp', '0005_alter_project_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='register.account'),
        ),
    ]
